# Generated by Django 4.1.7 on 2023-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("runner_file", models.FileField(upload_to="runner")),
                ("should_run", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Configuration",
            },
        ),
    ]
