# Generated by Django 4.1.7 on 2023-03-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuration",
            name="skip_traced",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="configuration",
            name="total_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="configuration",
            name="runner_file",
            field=models.FileField(blank=True, upload_to="runner"),
        ),
    ]
