# Generated by Django 4.1.7 on 2023-03-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("runner", "0002_configuration_skip_traced_configuration_total_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configuration",
            name="runner_file",
            field=models.FileField(blank=True, null=True, upload_to="runner"),
        ),
    ]
